from flask import url_for
def generate_iiif_manifest(mmif_str):
    # mmif_obj = mmif.Mmif(mmif_str)
    # # get all views with timeframe annotations from mmif obj
    # tf_views = mmif_obj.get_all_views_contain(AnnotationTypes.TimeFrame.value)
    # # for all timeframe annotations
    #
    # for view in tf_views:
    #     # get
    # # generate a iiif thing
    url = url_for('static', filename='video/cpb-aacip-29-00ns1swq.h264.mp4')

    return ('{\n'
            '    "id": "http://dlib.indiana.edu/iiif_av/lunchroom_manners",\n'
            '    "type": "Manifest",\n'
            '    "label": "Sample Newshour",\n'
            '    "description": "A sample Newshour Video",\n'
            '    "sequences": [\n'
            '        {\n'
            '            "id": "http://dlib.indiana.edu/iiif_av/lunchroom_manners/sequence/1",\n'
            '            "type": "Sequence",\n'
            '            "canvases": [\n'
            '                {\n'
            '                    "id": "http://dlib.indiana.edu/iiif_av/lunchroom_manners/canvas/1",\n'
            '                    "type": "Canvas",\n'
            '                    "label": "A sample Newshour Video",\n'
            '                    "description": "a sample newshour video from the aapb",\n'
            '                    "height": 360, \n'
            '                    "width": 480, \n'
            '                    "duration": 660,\n'
            '                    "content": [\n'
            '                        {\n'
            '                            "id": "...",\n'
            '                            "type": "AnnotationPage",\n'
            '                            "items": [\n'
            '                                {\n'
            '                                    "id": "...",\n'
            '                                    "type": "Annotation",\n'
            '                                    "motivation": "painting",\n'
            '                                    "body": [\n'
            '                                        {\n'
            '                                            "type": "Choice",\n'
            '                                            "choiceHint": "user",\n'
            '                                            "items": [\n'
            '                                                {\n'
            '                                                    "id": "' + url + '",\n'
            '                                                    "type": "Video",\n'
            '                                                    "label": "High",\n'
            '                                                    "format": "video/mp4"\n'
            '                                                }\n'
            '                                            ]\n'
            '                                        }\n'
            '                                    ],\n'
            '                                    "target": "http://dlib.indiana.edu/iiif_av/canvas/1"\n'
            '                                }\n'
            '                            ]\n'
            '                        }\n'
            '                    ]\n'
            '                }\n'
            '            ]\n'
            '        }\n'
            '    ],\n'
            '    "structures": [\n'
            '        {\n'
            '            "id": "http://dlib.indiana.edu/iiif_av/lunchroom_manners/range/3",\n'
            '            "type": "Range",\n'
            '            "label": "SMPTE Bars",\n'
            '            "members": [\n'
            '                {\n'
            '                    "id": "http://dlib.indiana.edu/iiif_av/lunchroom_manners/canvas/1#t=0,59",\n'
            '                    "type": "Canvas"\n'
            '                }\n'
            '            ]\n'
            '        },\n'
            '        {\n'
            '            "id": "http://dlib.indiana.edu/iiif_av/lunchroom_manners/range/3",\n'
            '            "type": "Range",\n'
            '            "label": "Slate",\n'
            '            "members": [\n'
            '                {\n'
            '                    "id": "http://dlib.indiana.edu/iiif_av/lunchroom_manners/canvas/1#t=60,112",\n'
            '                    "type": "Canvas"\n'
            '                }\n'
            '            ]\n'
            '        }\n'
            '    ]\n'
            '}\n')

